"""
BBB Fleet 2: Bounty Hunters — Agent 9: Broadcaster (Submission Formatter)
==========================================================================
Phase 6 agent. Formats evidence bundles and drafts into clean, 
sterile markdown for final broadcast and tracking.
"""

import asyncio
import json
from datetime import datetime

AGENT_ID = 9
AGENT_NAME = "B2 Broadcaster"

def format_sterile_markdown(payload: dict) -> str:
    """Formats the final submission into a sterile, platform-neutral markdown document."""
    
    title = payload.get("bounty_title", "Unknown Bounty")
    bounty_id = payload.get("bounty_id", "Unknown ID")
    platform = payload.get("platform", "Unknown Platform").upper()
    
    evidence = payload.get("evidence", {})
    bundle_id = evidence.get("bundle_id", "N/A")
    sandbox_id = evidence.get("sandbox_id", "N/A")
    evidence_hash = evidence.get("sha256_hash", "N/A")
    
    draft = payload.get("draft", "No draft provided.")
    poc = payload.get("poc", "No PoC provided.")
    
    # Sterile Markdown Template
    md = f"""# {title} ({platform} - {bounty_id})

## Evidence Chain
- **Evidence Bundle ID**: `{bundle_id}`
- **Sandbox Environment**: `{sandbox_id}`
- **Verification Hash (SHA256)**: `{evidence_hash}`
- **Generated At**: `{datetime.utcnow().isoformat()} UTC`

---

## Vulnerability Detail
{draft}

---

## Proof of Concept (PoC)
The following PoC was executed deterministically 3 times in the sandbox environment, yielding identical results.

```python
{poc}
```

---
*Generated by BBB Fleet 2 Validation Pipeline.*
"""
    return md


def local_broadcast_log(markdown_payload: str, platform: str):
    """
    Simulates broadcasting the payload to external channels (e.g., Farcaster/Telegram).
    Currently implemented as a local sterile log.
    """
    print(f"[{AGENT_NAME}] Broadcast Channel: {platform.upper()}")
    print("="*60)
    print(markdown_payload)
    print("="*60)


async def run(comms, context: dict = None) -> dict:
    """Main execution block for Broadcaster."""
    payload = context or {}
    platform = payload.get("platform", "algora")
    
    print(f"[{AGENT_NAME}] Phase 6: FORMATTING & BROADCASTING submission...")
    
    # Generate the sterile markdown
    formatted_body = format_sterile_markdown(payload)
    
    # "Broadcast" to local logs
    local_broadcast_log(formatted_body, platform)
    
    result = {
        "agent": AGENT_NAME,
        "phase": "formatting",
        "formatted_submission": formatted_body,
        "timestamp": datetime.utcnow().isoformat()
    }

    if comms:
        await comms.save_pipeline_log("phase_6_formatting", f"Formatted sterile submission for {platform}")

    return result


async def main():
    from core.bounty_comms import BountyComms
    comms = BountyComms(AGENT_ID, AGENT_NAME)
    await comms.startup()
    
    # Mock run
    test_payload = {
        "bounty_title": "Reentrancy in StakingPool",
        "bounty_id": "SHERLOCK-1002",
        "platform": "sherlock",
        "evidence": {
            "bundle_id": "EV-992384",
            "sandbox_id": "bbb_sandbox_20260806_abc123",
            "sha256_hash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        },
        "draft": "The `withdraw()` function in `StakingPool.sol` fails to update the user's balance before making an external call, allowing for reentrancy.",
        "poc": "def test_reentrancy():\n    assert pool.balance == 0"
    }
    
    await run(comms, test_payload)
    await comms.shutdown("Broadcasting completed", "", "")

if __name__ == "__main__":
    asyncio.run(main())
